version: '3'
# Run a full battery of test on all endpoints using https://pypi.org/project/schemathesis/
# This file sets up a db that allows testing alerts related endpoints.

services:
  api:
    environment:
      - 'RUN=uvicorn app.main:app --host 0.0.0.0 --port 80'
      - POSTGRES_HOST=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=!ChangeMe!
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
    #
    depends_on:
      - testdb
    networks:
      - prism
  testdb:
    image: kartoza/postgis:12.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=!ChangeMe!
    networks:
      - prism

networks:
  prism:
