version: "3"
# Run a full battery of test on all endpoints using https://pypi.org/project/schemathesis/
# This file sets up a db that allows testing alerts related endpoints.

services:
  api:
    volumes:
      - ./app:/app
    environment:
      - "RUN=uvicorn app.main:app --host 0.0.0.0 --port 80"
      - POSTGRES_HOST=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=!ChangeMe!
      - KOBO_PW=test
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
  testdb:
    image: kartoza/postgis:12.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=!ChangeMe!

  frontend:
    # small wrapper around the frontend code to make it easier to run
    # python tests against it
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    command: yarn start
    environment:
      - REACT_APP_COUNTRY=cambodia
    ports:
      - "3000:3000"
    volumes:
      - ../common:/common
      - ../frontend:/frontend

networks:
  testnet:
